/**
 * Clinical network adapter contract.
 *
 * This is the single most important interface in the platform. Everything
 * downstream — pipeline, CRM, storefront, portals — talks to *this*, never to
 * a specific vendor. AcmeHealth is one implementation of it, not the shape of it.
 *
 * Why it exists: a platform wired directly to one clinical network can only
 * ever be sold to that network's customers. An adapter means adding a network
 * is a new file, not a rewrite — and it's what makes the platform sellable in
 * markets where AcmeHealth doesn't operate at all.
 *
 * Design rules for anyone adding an adapter:
 *
 *   1. Nothing vendor-specific leaks past this boundary. No AcmeHealth field
 *      names, no AcmeHealth error codes, no AcmeHealth status vocabulary.
 *   2. Nothing US-specific is assumed. Addresses, phone numbers, identifiers
 *      and regulatory regime are all region-carrying.
 *   3. Adapters declare what they can do. The platform adapts to the network's
 *      capabilities rather than assuming every network has video visits, labs
 *      or automated refills.
 *   4. Adapters are stateless and side-effect free beyond the network call.
 *      Persistence, retries and idempotency belong to the platform.
 */

// ---------------------------------------------------------------- identity

/** ISO 3166-1 alpha-2. Region is explicit everywhere it could matter. */
export type CountryCode = string;

/**
 * Deliberately not US-shaped. `subdivision` is state / province / county /
 * prefecture; `postalCode` is not assumed to be five digits. A network that
 * requires a two-letter US state validates that in its own adapter.
 */
export interface Address {
  line1: string;
  line2?: string;
  city: string;
  subdivision?: string;
  postalCode?: string;
  country: CountryCode;
}

export interface PatientIdentity {
  firstName: string;
  lastName: string;
  /** ISO 8601 date, YYYY-MM-DD. Adapters format for their own vendor. */
  dateOfBirth: string;
  sex: "male" | "female" | "other";
  email: string;
  /** E.164, e.g. +15555550123. Never a locally-formatted string. */
  phone: string;
  address: Address;
}

// -------------------------------------------------------------- submission

export interface QuestionAnswer {
  /** Stable key from the questionnaire definition, not display text. */
  key: string;
  question: string;
  answer: string | string[];
  /** Present for multiple-choice; adapters that need the option list use it. */
  options?: string[];
}

export interface LabResult {
  testName: string;
  value: string;
  units?: string;
  referenceRange?: string;
  collectedOn: string;
  reportedOn?: string;
  sampleSource?: string;
}

export interface RequestedTreatment {
  /** Our product identifier. Adapters map it via `networkRefs`. */
  sku: string;
  name: string;
  strength?: string;
  quantity?: string;
  refills?: string;
  daysSupply?: string;
  /** Vendor identifiers for this product, e.g. { medId: "..." }. */
  networkRefs: Record<string, string>;
}

export interface VisitSubmission {
  /** Our identifier, generated by the platform. Guaranteed unique. */
  masterId: string;
  tenantId: string;
  /** Which programme this is, e.g. "weight_loss". Adapters map to visitType. */
  program: string;
  region: CountryCode;

  patient: PatientIdentity;
  answers: QuestionAnswer[];
  treatments: RequestedTreatment[];

  /** Signed consent records. Networks generally require at least one. */
  consents: Array<{ type: string; version: string; signedAt: string }>;

  /** Optional, capability-dependent. */
  labResults?: LabResult[];
  photos?: Array<{ mimeType: string; data: Uint8Array; kind?: string }>;
  identityVerification?: { verified: true; referenceId: string };
  pharmacyId?: string;

  /** Per-tenant vendor configuration — API keys, company identifiers. */
  networkConfig: Record<string, unknown>;
}

// ------------------------------------------------------------------ result

export type SubmissionErrorCode =
  /** Our payload was wrong. This is a bug on our side — alert engineering. */
  | "VALIDATION_FAILED"
  /** Patient's region isn't served. Expected; surface kindly. */
  | "REGION_NOT_SUPPORTED"
  /** Same patient submitted recently, possibly via another operator. */
  | "DUPLICATE_RECENT_VISIT"
  /** Clinically ineligible per the network's rules. */
  | "PATIENT_INELIGIBLE"
  /** Credentials rejected. */
  | "AUTHENTICATION_FAILED"
  | "RATE_LIMITED"
  /** Transport failure. Safe to retry. */
  | "NETWORK_ERROR"
  | "UNKNOWN";

export interface SubmissionError {
  code: SubmissionErrorCode;
  message: string;
  /** The vendor's own code, kept so specific handling stays possible. */
  vendorCode?: string;
  retryable: boolean;
  /** For DUPLICATE_RECENT_VISIT — when a retry becomes viable. */
  retryAfter?: string;
}

export type VisitSubmissionResult =
  | {
      ok: true;
      /** The network's identifier for this visit, if it issues one. */
      networkVisitId?: string;
      /** Only for networks supporting synchronous/video visits. */
      scheduleUrl?: string;
    }
  | { ok: false; error: SubmissionError };

// ------------------------------------------------------------------ status

/**
 * The platform's own status vocabulary. Every network's states map onto
 * these, so the pipeline never learns a vendor's words.
 */
export type NormalizedVisitStatus =
  | "SUBMITTED"
  | "UNDER_REVIEW"
  | "NEEDS_INFO"
  | "SCHEDULED"
  | "PRESCRIBED"
  | "REFERRED"
  | "CANCELED";

export interface Prescription {
  name: string;
  strength?: string;
  quantity?: string;
  refills?: string;
  prescriberName?: string;
  vendorRxId?: string;
  pharmacyNotes?: string;
}

export interface NetworkVisitState {
  networkVisitId?: string;
  status: NormalizedVisitStatus;
  vendorStatus?: string;
  prescriptions?: Prescription[];
  updatedAt?: string;
}

// ------------------------------------------------------------------ events

export type NormalizedEventType =
  | "visit.status_changed"
  | "visit.canceled"
  | "prescription.written"
  | "message.from_provider"
  | "message.from_support"
  | "appointment.scheduled"
  | "appointment.rescheduled"
  | "appointment.canceled"
  | "appointment.no_show"
  | "order.processing"
  | "order.shipped"
  | "order.delivered"
  | "shipment.in_transit"
  | "shipment.out_for_delivery"
  | "shipment.delivered"
  | "shipment.failed"
  | "lab.requisition_created"
  | "lab.kit_shipped"
  | "lab.sample_received"
  | "lab.results_ready";

export interface NormalizedEvent {
  type: NormalizedEventType;
  /** Our masterId — how the event is joined back to a visit. */
  masterId: string;
  occurredAt?: string;
  status?: NormalizedVisitStatus;
  prescriptions?: Prescription[];
  message?: { body: string; authorName?: string; isMedia?: boolean };
  order?: { orderId: string; carrier?: string; tracking?: string; trackingUrl?: string };
  documents?: Array<{ kind: string; mimeType: string; data: Uint8Array }>;
  /**
   * Stable key for deduplication. Many networks send no event id and no
   * timestamp, so adapters synthesise one — typically a hash of the body.
   */
  idempotencyKey: string;
  /** The untouched vendor payload, retained for audit. */
  raw: unknown;
}

export type WebhookVerification =
  | { trusted: true }
  /**
   * The network offers no way to authenticate its callbacks. The platform
   * then treats the event as an untrusted hint: enqueue it, then re-read
   * authoritative state via `getVisit`. Never a reason to trust the payload.
   */
  | { trusted: false; reason: "no_verification_available" | "signature_invalid" };

// ------------------------------------------------------------ capabilities

/**
 * What a given network can actually do. The platform reads this and adapts —
 * hiding video booking for networks without it, skipping refill automation
 * where it isn't supported.
 */
export interface NetworkCapabilities {
  asyncVisits: boolean;
  videoVisits: boolean;
  labOrders: boolean;
  pharmacyFulfilment: boolean;
  providerMessaging: boolean;
  automatedRefills: boolean;
  photoUpload: boolean;
  /** Verifiable webhooks. False means untrusted-hint handling. */
  webhookVerification: boolean;
  /** Regions this network serves. Empty means unrestricted. */
  supportedRegions: CountryCode[];
}

// ----------------------------------------------------------------- adapter

export interface ClinicalNetworkAdapter {
  /** Stable key stored on `tenants.clinical_network`. */
  readonly id: string;
  readonly displayName: string;
  readonly capabilities: NetworkCapabilities;

  submitVisit(submission: VisitSubmission): Promise<VisitSubmissionResult>;

  /**
   * Authoritative read. Used for reconciliation, and as the source of truth
   * whenever webhooks cannot be verified.
   */
  getVisit(
    masterId: string,
    config: Record<string, unknown>
  ): Promise<NetworkVisitState | null>;

  /** Confirms an inbound callback genuinely came from the network. */
  verifyWebhook(
    rawBody: string,
    headers: Record<string, string>,
    config: Record<string, unknown>
  ): WebhookVerification;

  /** Vendor payload to our vocabulary. Null for events we don't model. */
  normalizeEvent(rawBody: string, headers: Record<string, string>): NormalizedEvent | null;

  // -- capability-gated ----------------------------------------------------

  sendPatientMessage?(
    masterId: string,
    body: string,
    config: Record<string, unknown>
  ): Promise<{ ok: boolean; error?: string }>;

  requestRefill?(
    masterId: string,
    treatment: RequestedTreatment,
    config: Record<string, unknown>
  ): Promise<VisitSubmissionResult>;
}
